package com.uca.dao;

import com.uca.entity.StickerEntity;
import com.uca.exceptions.ServiceException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

public class StickersDAO extends _Generic<StickerEntity> {

    @Override
    public ArrayList<StickerEntity> getAll() throws ServiceException {
        try {
            ArrayList<StickerEntity> entities = new ArrayList<>();
            PreparedStatement preparedStatement = this.connect.prepareStatement("SELECT * FROM stickers ORDER BY id ASC;");
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                StickerEntity entity = new StickerEntity();
                entity.setId(resultSet.getInt("id"));
                entity.setDescription(resultSet.getString("description"));
                entity.setColor(resultSet.getString("color"));
                entities.add(entity);
            }

            return entities;
        } catch (SQLException e){
            e.printStackTrace();
            throw new ServiceException("Could not get stickers.");
        }
    }

    @Override
    public void deleteById(int id) throws ServiceException {
        try {
            PreparedStatement preparedStatement = this.connect.prepareStatement("DELETE FROM assigned_stickers WHERE sticker_id = ?;");
            preparedStatement.setInt(1, id);
            preparedStatement.executeUpdate();

            preparedStatement = this.connect.prepareStatement("DELETE FROM stickers WHERE id = ?;");
            preparedStatement.setInt(1, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e){
            e.printStackTrace();
            throw new ServiceException("Could not delete sticker id " + id);
        }
    }

    @Override
    public StickerEntity create(StickerEntity obj) throws ServiceException {
        try {
            PreparedStatement preparedStatement = this.connect.prepareStatement("INSERT INTO stickers(color, description) VALUES(?,?)", Statement.RETURN_GENERATED_KEYS);
            preparedStatement.setString(1, obj.getColor());
            preparedStatement.setString(2, obj.getDescription());
            preparedStatement.executeUpdate();

            //Auto-incremented values generated by the current PreparedStatement object
            ResultSet res = preparedStatement.getGeneratedKeys();
            res.next();
            obj.setId(res.getInt(1));

            return obj;
        } catch (SQLException e){
            e.printStackTrace();
            throw new ServiceException("Could not create sticker.");
        }
    }

    @Override
    public StickerEntity getById(int id) throws ServiceException {
        throw new ServiceException("Not implemented !");
    }

    @Override
    public void update(int id, StickerEntity obj) throws ServiceException {
        throw new ServiceException("Not implemented !");
    }

}
